my_string = input('Сколько тебе лет: ')
print('Привет,',my_string)
print(len(my_string))
my_string = 'Сколько тебе лет'
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string [0])
print(my_string[-1])